version: '3.8'
services: 
  fastify_api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
    command: >
      sh -c "yarn clean-build:api && yarn dev"
    expose: 
      - "3051"
    ports:
      - "3051:3051"
    environment: 
      NODE_ENV: development
    depends_on: 
      - postgres_db
    environment: 
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/fastify_api?schema=public

  postgres_db:
    image: postgres:latest
    expose: 
      - "5432"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_DB=fastify_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres